### ISSUE TITLE
Broken from @octokit/rest v19.0.7

### ISSUE THREAD

**Issue by futhr** [mheap/octokit-commit-multiple-files#110]
Hi, I get this error when using (currently latest) `@octokit/rest` v19.0.13: 

```
TypeError: Cannot destructure property 'decorations' of 'endpointMethodsMap.get(...).get(...)' as it is undefined.
    at Object.get (/node_modules/@octokit/plugin-rest-endpoint-methods/dist-node/index.js:1929:13)
```

To solve the issue I have to lock dependency to a previous version  `"@octokit/rest": "19.0.6"`

So it seems to be related to changes in `@octokit/plugin-rest-endpoint-methods` v7.x

See: https://github.com/octokit/rest.js/releases/tag/v19.0.7

**Comment by tresabhi** [comment]
+1

**Comment by mheap** [comment]
Thanks for flagging. I'm struggling to find OSS time at the moment, so any PRs would be gratefully received. 

I'll try and get to this in 2-3 weeks if no PR is raised in that time
