### ISSUE TITLE
Return commit SHA(s)

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [mheap/octokit-commit-multiple-files#46]
I would like to get the SHA(s) of the commits that were created as part of the return value (currently only `branchName`).

**Comment by mheap** [comment]
This is resolved in #52 and will be released as v2.0.0

**Comment by mheap** [comment]
This is now available in v4.0.0. The return value is an object that contains a `commits` key. All of the information returned by the GitHub API is available
